### ISSUE TITLE
How do I test a hook that relies on a closure?

### ISSUE THREAD

**Issue by Swoodend** [testing-library/react-hooks-testing-library#131]
### What is your question:

How do I test a hook that relies on a closure over some state? Let's say I have some code that looks like this:

```
const useUsers = () => {

  const [users, setUsers] = useState([]);
  const [selectedUser, setSelectedUser] = useState();

  const onSelectUser = useCallback((event) => {
	const { value : userId } = event.target;

	const selectedUser = users.filter(user => user.id === userId)[0];
	setSelectedUser(selectedUser);
  }, [users]);

  return {
    users,
    setUsers,
    onSelectUser
  };

}

```

For my unit test, I want to make sure that the `selectedUser` is set when`onSelectUser` is called. Because  `onSelectUser` iterates over the `users` array held in state I need this closure to be maintained.

My test looks like this

```
const users = [{id: 1, name: 'alice'}, {id:2, name:'bob'}];
const event = { target: { value: 2 }};

const { result } = renderHook(() => useUsers());

const { onSelectUser, setUser } = result.current;

act(() => {
        // trying to set the users array here so onSelectUser will have closure over it
	setUsers(users);

       // whenever this function runs the users array is undefined
	onSelectUser(event);
});

// fails as result.current.selectedUser is undefined
expect(result.current.selectedUser).toBe(users[1]);
```

Is there something I can do to get this to work? Or is the library not intended to be used this way?

**Comment by mpeyper** [comment]
There are 3 reasons why this is not working.

1. You are not returning `selectedUser` from your hook so `result.current.selectedUser` will always be `null`.  Update it to:

```js
const useUsers = () => {

  const [users, setUsers] = useState([]);
  const [selectedUser, setSelectedUser] = useState();

  const onSelectUser = useCallback((event) => {
	const { value : userId } = event.target;

	const selectedUser = users.filter(user => user.id === userId)[0];
	setSelectedUser(selectedUser);
  }, [users]);

  return {
    users,
    setUsers,
    onSelectUser
  };

}
```

2. You are destructuring `result.current`. This "locks in" the initial `onSelectUser` callback so when it is called after `setUsers`, the callback has closed over the initial empty `users` array.  Just use `setUsers` and `onSelectUser` directly off `result.current` instead:

```js
const users = [{id: 1, name: 'alice'}, {id:2, name:'bob'}];
const event = { target: { value: 2 }};

const { result } = renderHook(() => useUsers());

act(() => {
	result.current.setUsers(users);
	result.current.onSelectUser(event);
});

expect(result.current.selectedUser).toBe(users[1]);
```

3. The above change is still not enough to get this test working as all of the state changes within a single `act` call are batched and applied after the block is complete, so the `onSelectUser` callback is not recalculated until it gets called, meaning it still uses the initial `users` array.  Separate the two updates into unique `act` calls so that they are no longer batched:

```js
const users = [{id: 1, name: 'alice'}, {id:2, name:'bob'}];
const event = { target: { value: 2 }};

const { result } = renderHook(() => useUsers());

act(() => {
	result.current.setUsers(users);
});

act(() => {
	result.current.onSelectUser(event);
});

expect(result.current.selectedUser).toBe(users[1]);
```

Now this test passes.  You can see it working in [this sandbox](https://codesandbox.io/s/react-hook-testing-ly1w2?fontsize=14&module=%2Fsrc%2Fexample.test.js&previewwindow=tests).

**Comment by Swoodend** [comment]
Thanks for your help mpeyper!
