### ISSUE TITLE
Concurrent mode

### ISSUE THREAD

**Issue by FredyC** [testing-library/react-hooks-testing-library#217]
I already open the issue for `@testing-library/react` (https://github.com/testing-library/react-testing-library/issues/509) and it might good idea to have a separate issue for tracking changes in this library as well. 

Given this library utilizes `react-test-renderer` instead of `react-dom` it might require slightly different implementation. However, it seems there are [no commits](https://github.com/facebook/react/commits/master/packages/react-test-renderer) to that package regarding concurrent mode.

@gaearon if you notice this issue by any chance, can you clarify if this something that wasn't simply covered yet and if there is a plan for it?

**Comment by mpeyper** [comment]
Thanks @FredyC!

Concurrent mode is still something I have to wrap my head around and what it means for this package.

I'm really curious to know if react-test-renderer is going to continue being supported going forward. It seems to have been forgotten or given minimal love in recent times. [An issue I raised with it](https://github.com/facebook/react/issues/15520) has gone unanswered for months.

**Comment by denniscual** [comment]
I tried to use the unstable API from React called `unstable_useMutableSource` to my state management library and my tests now are failing due to the fact the library doesn't have support for CM. 

Snapshot error:
![image](https://user-images.githubusercontent.com/17754712/92089801-392f4a80-ee01-11ea-92ca-c1f40aa9eddf.png)

I can say supporting CM for now is kinda early but its good that this library in the future could provide support on CM mode so that library author can also rely to this library. Can I say at least experimental version? I guess.

**Comment by mpeyper** [comment]
Hi @denniscual,

This library uses `react-test-renderer` under the hood for rendering the test component that calls your hook.  If `unstable_useMutableSource` is not working, it's because the renderer does not support it (we don't do anything special to make any specific hooks work).

As far as I'm aware, `unstable_useMutableSource` should work with or without concurrent mode too, so I'm not sure what we can do to help with this one.

**Comment by denniscual** [comment]
@mpeyper hey thanks for the information. Im not aware of the implementation details of this library. That's being said, I assume upgrading to a version of `react-test-renderer` which support the `unstable_useMutableSource` could suffice for this problem. Of course, I reached out to you guys because the library which I'm working on doesn't work because I used the said api and if you can see the above image, there is a `TypeError` which leads to this library.

Thanks btw.

**Comment by joshuaellis** [comment]
I'm not sure we should be aiming to support unstable APIs & should wait until concurrent mode is more solidified with React. However, looking at this [comment](https://github.com/testing-library/react-testing-library/issues/509#issuecomment-594030917) in RTL, you might be able to use concurrent mode with react-dom, which we'll be supporting as a renderer soon, you can see it's progress here – #510 

If anyone feels like there's more to discuss then we can re-open this issue.
