### ISSUE TITLE
How can I test hook that changes without me?

### ISSUE THREAD

**Issue by OlegBrony** [testing-library/react-hooks-testing-library#307]
### What is your question:
I have a hook useTimer and I want to test its state. here is all code - https://codesandbox.io/s/frosty-rgb-6im7v
and it's passing the tests, but there is multiple errors is the console. how can I fix it? I probably should place it in act func, but how can I do this, if the timer (after I ran play func) is updates itself without my help?

**Comment by mpeyper** [comment]
This isn't really related to this library, but to react hooks in general.  You will see those errors any time the hooks state is updated outside of an `act` block.  Because the interval is triggering the state to update, while you are waiting at the `delay(2)` line, the updates are outside of any `act`s (I suspect you know this, but adding context for anyone else reading this).

To get around this, you can pass an `async` function to `act` and it will allow all updates that occur while before that function resolves to be wrapped in an `act` block.  The most basic version of this looks looks like

```js
await act(() => delay(2));
```

or

```js
await act(async () => await delay(2));
```

depending on how explicit you want to be with what is `async`/`await` and what is a function that returns a promise.

Alternatively, you can change your `delay` utility to handle the `act` wrapping for you.  This is a good solution if you will end up with lots of tests using the `delay` utility.

```js
const delay = s => act(() => 
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, s * 1000);
  }));
```

Finally, having arbitrary delays in your tests can often lead to long running and brittle test suites.  It's often safe to wait for some condition to be met instead just time passing.  This library provides a [set of helpers](https://react-hooks-testing-library.com/reference/api#async-utilities) for doing this that automatically handle the `act` wrapping for you.  This allows you to replace the `delay` call with something like:

```js
await hook.wait(() => hook.result.current.sec === "02")
```

Please note the the condition in the `wait` is just an example that roughly replicates what you had.  You would know best what you are actually trying to achieve (perhaps `waitForNextUpdate` is all you actually require to ensure the time has actually ticked once before pausing... I dunno?).

**Comment by OlegBrony** [comment]
looks like exactly what I was looking for. many thanks!
