### ISSUE TITLE
react hooks + mobx

### ISSUE THREAD

**Issue by elle510** [testing-library/react-hooks-testing-library#382]
### What is your question:

MyComponent .js

```js
const MyComponent = observer(() => {
    const myMethod = useCallback(() => 'print myMethod');
});

export default MyComponent;
```

MyComponent.test.js

```js
const { result } = renderHook(() => MyComponent());
const print = result.current.myMethod();

expect(print).toEqual('print myMethod');
```

not working(occur error)

support mobx?

**Comment by mpeyper** [comment]
I'm not super familiar with mobx, but I believe `observer` returns a component (as your naming would suggest), not a hook function.  However, even if it did return a hook, you are not returning anything from your function, so it will never be available on `result.current`.

I think you want to be using `@testing-library/react` and actually render the component instead of using this library.
