### ISSUE TITLE
React Hooks Results TypeError: Cannot read property 'current' of undefined. {"current": undefined, "error": undefined}

### ISSUE THREAD

**Issue by nikitapandya** [testing-library/react-hooks-testing-library#403]
- `react-hooks-testing-library` version: 3.2.1
- `react-test-renderer` version: 16.13.1
- `react` version: 16.13.1
- `npm` (or `yarn`) version: 5.6.0
"@types/react": "16.9.4",

### Relevant code or config:

```js
jest.mock('./useFileReader');
describe('useTextField', () => {
  test('should have an handle select method', () => {
    const { result } = renderHook(() => useFileReader());
    expect(result.current.handleSelect).toBeInstanceOf(Function)
    act(() => {
      result.current.handleSelect([new File(['foo'], 'foo.txt')]);
    });
  });
});

```

### What you did:

Trying to test my filereader custom hook. Which creates an instance of the file reader api, process a file and uploads. 

### What happened:

Keep getting error "Cannot read property 'current' of undefined"
This is what the results object is: Received: {"current": undefined, "error": undefined}
Fails at first expect statement: expect(result.current.handleSelect).toBeInstanceOf(Function)

Without mocking the hook at top of file, get an error regarding the context that I am using in the hook. 

### Reproduction:
Codesandbox in progress. 

### Suggested solution:

Reading similar issues, I assumed it was a react version issue. Double checked with another repo using the testing-library/react-hooks package and our versions match. Tests seem to run fine for that project. 

Want to see if I am using this package currently, have any version mismatch issues. Or potentially something is wrong with my hook (which functions in the UI fine)

**Comment by mpeyper** [comment]
It's a bit hard to help without seeing what the hook is actually doing.

I suspect the mock is returning `undefined` because you haven't mocked out a return value ([see their docs](https://jestjs.io/docs/en/mock-functions#mocking-modules)), but I have to wonder what the test is testing if your mocking the entire hook your trying to render, so I'm much more interested in the error you're seeing when you don't mock and trying to get that working for you instead.

If it's mentioning context, do you just need to [provide a context provider as a `wrapper`](https://react-hooks-testing-library.com/usage/advanced-hooks#context) in your test?

**Comment by mpeyper** [comment]
ok, I'll close this now. Let me know if you want to pick this up again and work through the issues.
