### ISSUE TITLE
Js heap out of momory when init the state with object.

### ISSUE THREAD

**Issue by HAHAHA44** [testing-library/react-hooks-testing-library#413]
Hello! 
I got a `JavaScript heap out of momory` bug in my terminal when use this library. But the custom hook runs well in browser.

```
<--- Last few GCs --->

[57358:0x1041cf000]   621390 ms: Mark-sweep (reduce) 4045.5 (4101.5) -> 4044.8 (4101.8) MB, 5843.7 / 0.0 ms  (average mu = 0.115, current mu = 0.001) allocation failure scavenge might not succeed
[57358:0x1041cf000]   628555 ms: Mark-sweep (reduce) 4045.8 (4101.8) -> 4045.1 (4102.0) MB, 7160.2 / 0.0 ms  (average mu = 0.056, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Dclare code: 
```
const useTest = (init: any) => {
  const [arr, setArr] = useState<any[]>([]);
  useEffect(() => {
    setArr(Array.from(init.arr));
  }, [init]);
  return arr;
};
```

Test code:
```
describe('test', () => {
  it('test init arr', () => {
    useTest({ arr: [] })
  })
})
```

No matter what object or array did I pass to the init.arr, it would cause the error. I tried to wrap the init object by useMemo, its useless. But if i pass a (string | number | null | undefined), it won`t get error.

**Comment by mpeyper** [comment]
Hi @HAHAHA44,

I'm assuming you're actually calling `useTest` inside `renderHook` (you'd be seeing a very different error if your aren't), so I'll try to explain what's going on for this test code:

```js
describe('test', () => {
  it('test init arr', () => {
    renderHook(() => useTest({ arr: [] }))
  })
})
```

The problem here arises from creating a new object (`{ arr: [] }`) inside the `renderHook` callback ever time the hook renders (this callback is what our test component calls each time it renders), so the flow goes something like this:

1. `renderHook(...)`
2. `useTest({ arr: [] })` (new reference)
3. `useEffect(..., [init])` (initial render, effect triggered)
4. `setArr(Array.from(init.arr))` (state changed, render triggered)
5. `renderHook(...)`
7. `useTest({ arr: [] })` (new reference)
8. `useEffect(..., [init])` (dependency changed, effect triggered)
9. `setArr(Array.from(init.arr))` (state changed, render triggered)
10. `renderHook(...)`
11. `useTest({ arr: [] })` (new reference)
12. `useEffect(..., [init])` (dependency changed, effect triggered)
13. `setArr(Array.from(init.arr))` (state changed, render triggered)
14. `renderHook(...)`
15. ... and we're looping

The quickest fix is to just move the creation of the object outside the `renderHook` callback:

```js
describe('test', () => {
  test('test init arr', () => {
    const props = { arr: [] }
    renderHook(() => useTest(props))
  })
})
```

This only works for the cases where you want to `setArr` from the result of the hook, e.g. by returning `setArr` from the function, but if you want to test the what a happens when new arguments are passed you can use the `initialProps` and `rerender` functionality:

```js
describe('test', () => {
  test('test init arr', () => {
    const { rerender } = renderHook((props) => useTest(props), {
      initialProps: { arr: ['initial value'] }
    })

    rerender({ arr: ['new value' ]})
  })
})
```

_(Note `initialProps` could have been used in the first example, but I've found most people prefer to just create their own variable.)_

You can find more details about this _in our docs_(https://react-hooks-testing-library.com/usage/basic-hooks#props).

**Comment by HAHAHA44** [comment]
Thank you for your reply, this solved my problem and I learned a lot from it.
