### ISSUE TITLE
Hook gets unmounted right after `renderHook`

### ISSUE THREAD

**Issue by vabatta** [testing-library/react-hooks-testing-library#478]
- `@testing-library/react-hooks` version: 3.4.2
- `react-test-renderer` version: ^16.13.1
- `react` version: 16.13.1
- `node` version: 12.18.3
- `npm` (or `yarn`) version: 6.14.6

### Relevant code or config:

Custom hook
```ts
import { DependencyList, useEffect, useRef, useState } from 'react';

export const useHttpRequest = <T>(
  url: string,
  init?: Omit<RequestInit, 'signal'>,
  deps?: DependencyList
) => {
  // ref to make sure the hook is properly mounted before firing the async fetch
  const isMounted = useRef(true);
  const [response, setResponse] = useState<T>();
  const [error, setError] = useState<Error>();
  const [pending, setPending] = useState(false);

  useEffect(() => {
    const abortController = new AbortController();
    const handleOrAborted = (cb: Function) => {
      // NOTE we don't report abort as an error because it means the component is begin unmounted
      if (!abortController.signal.aborted) cb();
    };
    const doFetch = async () => {
      handleOrAborted(() => setPending(true));

      try {
        const fetchResponse = await fetch(url, { ...init, signal: abortController.signal });
        if (fetchResponse.ok) {
          const json = await fetchResponse.json();
          handleOrAborted(() => setResponse(json));
        } else {
          handleOrAborted(() => setError(new Error(`STATUS_${fetchResponse.status}`)));
        }
      } catch (error_) {
        handleOrAborted(() => setError(error_));
      } finally {
        handleOrAborted(() => setPending(false));
      }
    };

    if (isMounted.current) {
      doFetch();
    }

    return () => {
      isMounted.current = false;
      abortController.abort();
    };
  }, deps);

  return { response, error, pending };
};
```

Hook test
```ts
import { renderHook, cleanup } from '@testing-library/react-hooks';
import { useHttpRequest } from './use-http-request';

describe('useHttpRequest', () => {
  const mockAPI = (resolvesTo: Promise<any>) =>
    jest.fn((url: string) =>
      url.endsWith('/api/test')
        ? Promise.resolve({
            ok: true,
            json: () => resolvesTo,
          })
        : Promise.reject(new Error(`${url} not mocked`))
    );

  beforeEach(() => {
    (global as any).fetch = mockAPI(Promise.resolve('foo'));
  });

  afterEach(() => {
    cleanup();
  });

  it('should return an array containing the correct types after initial render', () => {
    const { result } = renderHook(() => useHttpRequest('test.com/api/test'));
    expect(typeof result.current.error).toBe('undefined');
    expect(typeof result.current.pending).toBe('boolean');
    expect(typeof result.current.response).toBe('undefined');
  });

  it('should return an array containing the correct types after resolving', async () => {
    const { result, waitForNextUpdate } = renderHook(() => useHttpRequest('test.com/api/test'));
	// the problem is happening here as the hook gets unmounted thus abort the mock request
    await waitForNextUpdate();
    expect(typeof result.current.error).toBe('undefined');
    expect(typeof result.current.pending).toBe('boolean');
    expect(typeof result.current.response).toBe('string');
  }, 500);
});
```

### Reproduction:

The code is available at https://codesandbox.io/s/react-testing-library-demo-forked-szh3s

### Problem description:

The test should be able to check that the hook resolved correctly, instead it timeout. The problem is that right after using `renderHook` the hooks seems to be unmounted before the actual test is ended.

**Comment by mpeyper** [comment]
I haven't looked thoroughly because I'm on my phone, and I'll take a better look later, but what happens if you default `deps` to `[]`?

Effects with no dependency array will run their cleanup and rerun the effect every render (i.e. state change). If you want it to run once, you need to pass an empty array.

**Comment by vabatta** [comment]
I actually don't want to run it once but have the consumer of the hook to decide what dependencies to pass. This means that I am basically mirroring the `useEffect` dependency list in the parameter, thus the behavior of that is correct.

**Comment by mpeyper** [comment]
Ok, but then the way you're calling it in your test is an issue.  If `deps` gets to `useEffect` as `undefined` (like it does in your tests now), then as soon as `setPending(true)` is called at the start of `doFetch`, a state change is queued and the hook will rerender.

Because there is no dependency array, on the subsequent render the effect cleans up, aborting the current request and flagging `isMounted.current` as `false`.  The effect reruns, running, but this time it does not call `doFetch` because the `isMounted.current` is `false`.  There are no more state changes to process so that effect (that is doing nothing) remains and no more renders are triggered and the test resumes.

There are no state changes to come from the initial promise because `handleOrAborted` suppresses them all so `waitForNextUpdate` never resolves (because there was no update).

Either changing `deps` to default to `[]` or changing the test to call `useHttpRequest('test.com/api/test'), undefined, [])` fixes this.  I understand that you want the request to run again if one of the consumers provided deps changes, but I'm proposing that if no deps are provided, their intention was not to rerun it on every render because it is creating state changes internally that will trigger the renders causing itself to become aborted.

I think the root of the issue is your misconception that `useEffect` cleanup equals unmounting.  Whilst cleanup occurs on unmount, it also occurs at other times.  The only way to use hooks to determine if unmounting has occurred is to have a dedicated effect for tracking it:

```js
  useEffect(() => {
    return () => {
      isMounted.current = false
    }
  }, [])
```

You'll notice if you implement `isMounted` this way, your test will call `doFetch` a lot more.

**Comment by vabatta** [comment]
Thanks for the exhaustive answer! Has for sure cleared a lot of my doubts. I will need to take a deeper look at this to better understand what is going on.
Yes, the codesandbox was acting really weirdly also when I was setting it up 👐
