### ISSUE TITLE
Can't mock react-router-dom useNavigate hook in jest unit test : navigate is not a function

### ISSUE THREAD

**Issue by chrys-exaucet** [testing-library/react-hooks-testing-library#588]
## 🐛 Bug Report

I cannot mock useNavigate hook when unit testing a custom hook with jest .
Similar: to  https://stackoverflow.com/questions/66284286/react-jest-mock-usenavigate/66880431#66880431
 

## To Reproduce

````js
//  useHome.ts

import { useNavigate } from 'react-router-dom';

const useHome = () => {

  const navigate = useNavigate();

  const handleClientChange = (id: number) => { navigate(`/client/${id}`);};


  return {
    handleClientChange,
  };
};


export {
  useHome,
};


````

````js

// useHome.test.ts
import { act, renderHook } from '@testing-library/react-hooks';
import { useHome } from './useHome';



const mockedNavigator = jest.fn();

jest.mock('react-router-dom', () => ({
  ...jest.requireActual('react-router-dom') as any,
  useNavigate: () => ({
    navigate: jest.fn().mockImplementation(() => ({})),
  }),
}));


describe('useHome', () => {

  describe('handleClientChanged', () => {

    it('should  navigate to a new client page', () => {

      const { result } = renderHook(() => useHome());

      act(() => {
        result.current.handleClientChange(2);                 // <------- error: navigate is not a function
      });

      expect(mockedNavigator).toHaveBeenCalled();
    });

  });

});



````

Throws 

````
TypeError: navigate is not a function
    at Object.handleSubmit
````

## Expected behavior

useNavigate hook is mocked.

## Link to repl or repo (highly encouraged)
https://codesandbox.io/s/usenavigate-unit-test-sxrf1?file=/src/useHome.test.ts

## envinfo
```
  System:
    - OS: Windows 10 10.0.19042
    - CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    - Node: 14.7.0  
    - Yarn: 1.22.10 
    - npm: 6.14.11 
```

**Here my stack**

- jest@26.6.0
- react-router@6.0.0-beta.0
-  react-router-dom@6.0.0-beta.0
-  react@17.0.1
-  typescript@4.2.3

**Comment by mpeyper** [comment]
The issue here is that `useNavigate` returns the `navigate` function directly but you are mocking it to return an object with the navigate function as a property:

```ts
const navigate = useNavigate();
```

vs.

```ts
useNavigate: () => ({
  navigate: jest.fn().mockImplementation(() => ({})),
}),
```

On top of that, the test is expecting `mockedNavigator` to be called, not the mocked `navigate` function you are creating when mocking the import.  Your tests passes if I change the import mocking to be:

```ts
jest.mock("react-router-dom", () => ({
  ...(jest.requireActual("react-router-dom") as any), // technically it passes without this too, but I'm not sure if its there for other tests to use the real thing so I left it in
  useNavigate: () => mockedNavigator,
}));
```

**Comment by chrys-exaucet** [comment]
Thanks @mpeyper ! You were totally right.

**Comment by Babatunde50** [comment]
> The issue here is that `useNavigate` returns the `navigate` function directly but you are mocking it to return an object with the navigate function as a property:
> 
> ```ts
> const navigate = useNavigate();
> ```
> 
> vs.
> 
> ```ts
> useNavigate: () => ({
>   navigate: jest.fn().mockImplementation(() => ({})),
> }),
> ```
> 
> On top of that, the test is expecting `mockedNavigator` to be called, not the mocked `navigate` function you are creating when mocking the import. Your tests passes if I change the import mocking to be:
> 
> ```ts
> jest.mock("react-router-dom", () => ({
>   ...(jest.requireActual("react-router-dom") as any), // technically it passes without this too, but I'm not sure if its there for other tests to use the real thing so I left it in
>   useNavigate: () => mockedNavigator,
> }));
> ```

Thank you 🙏🙏🙏🙏

**Comment by arjunByldd01** [comment]
Here is the solution to mock useNavigate hook for vitest and jest.

IMPORTANT:- Use react-router instead of react-router-dom

Component File

import { useNavigate } from 'react-router';
const navigate = useNavigate();

  const onClick = () => {
  navigate('/setup');
};

<button  onClick={onClick} > Click  </button>
Mock --> test.js file

const mockedUsedNavigate = vi.fn(); // keep the declaration of this on top of file. make it very first variable in the file.
 const mockedUsedNavigate = vi.fn();  //keep it at top of file
 
//Here we are mocking partially means only useNavigate we are mocking and remaining we are required actual.
beforeEach(() => {
    vi.mock('react-router', () => {
      return {
        ...vi.importActual('react-router'),  // for vitest 
        ...jest. requireActual('react-router') // for jest
        useNavigate: () => mockedUsedNavigate,
      };
    });
  });

  describe('...........', () => {
          test('.........'), async()=>{

            render(.......)
            
           await waitFor(() => expect(mockedUsedNavigate).toBeCalledWith('/path'));
           await waitFor(() => expect(mockedUsedNavigate).not.toBeCalledWith('/another path));
          }
  }

**Comment by arjundangi01** [comment]
Here is the solution to mock useNavigate hook for vitest and jest.

IMPORTANT:-  Use react-router instead of react-router-dom


**Component File**
   
  ```
 import { useNavigate } from 'react-router';
  const navigate = useNavigate();

    const onClick = () => {
    navigate('/setup');
  };
  
  <button  onClick={onClick} > Click  </button>
```
          

 **Mock --> test.js file**
 
1. const mockedUsedNavigate = vi.fn();  // keep the declaration of this on top of file. make it very first variable in the file.

```
 const mockedUsedNavigate = vi.fn();  //keep it at top of file
 
//Here we are mocking partially means only useNavigate we are mocking and remaining we are required actual.
beforeEach(() => {
    vi.mock('react-router', () => {
      return {
        ...vi.importActual('react-router'),  // for vitest 
        ...jest. requireActual('react-router') // for jest
        useNavigate: () => mockedUsedNavigate,
      };
    });
  });

  describe('...........', () => {
          test('.........'), async()=>{

            render(.......)
            
           await waitFor(() => expect(mockedUsedNavigate).toBeCalledWith('/path'));
           await waitFor(() => expect(mockedUsedNavigate).not.toBeCalledWith('/another path));
          }
  }
 
```
