### ISSUE TITLE
useCallback is not called when dependencies are changed

### ISSUE THREAD

**Issue by jackall3n** [testing-library/react-hooks-testing-library#590]
- `react-hooks-testing-library` version: `^5.1.1`
- `react` version: `^17.0.2`
- `react-dom` version (if applicable): `^17.0.2`
- `react-test-renderer` version (if applicable): `n/a`
- `node` version: `v12.18.1`
- `npm` (or `yarn`) version: `1.22.10`

#### The Hook
```typescript
import { useCallback, useEffect } from "react";

function useCallbackHook(callback: () => void | undefined, deps: any[]) {
  const cb = useCallback(callback, deps);

  useEffect(() => {
    console.log("dependencies changed", deps);
  }, deps)

  useEffect(() => {
    console.log("callback changed");

    cb();
  }, [cb])
}

export default useCallbackHook;
```

#### The Test
```typescript
import { renderHook } from '@testing-library/react-hooks'
import useCallbackHook from './useCallbackHook';

describe('useCallbackHook', () => {
  it('should change the effect', async () => {
    const callback = jest.fn();

    const { rerender } = renderHook(({ dep }) => useCallbackHook(callback, [dep]), {
      initialProps: {
        dep: 'initial'
      }
    })

    rerender({ dep: "#1" });
    rerender({ dep: "#2" });
    rerender({ dep: "#3" });

    expect(callback).toHaveBeenCalledTimes(3);
  });
});
```

#### The Console
```properties
console.log
    dependencies changed [ 'initial' ]

      at src/utils/useCallbackHook.ts:7:13

  console.log
    callback changed

      at src/utils/useCallbackHook.ts:11:13

  console.log
    dependencies changed [ '#1' ]

      at src/utils/useCallbackHook.ts:7:13

  console.log
    dependencies changed [ '#2' ]

      at src/utils/useCallbackHook.ts:7:13

  console.log
    dependencies changed [ '#3' ]

      at src/utils/useCallbackHook.ts:7:13


Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)

Expected number of calls: 3
Received number of calls: 1
```

### What you did:

I've created a hook that takes in a callback and an array of dependencies. Inside the hook it uses `useCallback` to memoize the hook argument and invokes it if it changes.

### What happened:

While in practise this works correctly, while testing `useCallback` does not re-invoke when dependencies change. You'll notice in the output that I write to the console using `useEffect` hooks when either the dependencies change. It is expected that because the dependencies change, that `useCallback` is re-run and the second `useEffect` is invoked, however, that is not the case.

I have tried replacing `useCallback(callback, deps)` with `useMemo(() => callback, deps)`, however, the same issue occurs.

I have also tried `wait(ing)For` and `act(ing)` with no luck. I assume I must be missing something.

https://reactjs.org/docs/hooks-reference.html#usecallback

**Comment by mpeyper** [comment]
Ok, so what's going on here is that `useCallback` does nothing but return the function you pass to it when the deps change or return the previous function if the deps don't change.  What this means is that by passing the same reference of `jest.fn()` to `useCallbackHook` each time the component renders, the reference of `cb` will never change.  Presumably in your actual code you are always calling it with something like `useCallbackHook(() => someFunction(dep), [dep])` which creates a new `callback` reference each time.

To get the same behaviour in your test, you need to change the call to be something like `useCallbackHook(() => callback(), [dep])` or you can change the implementation of the `useCallback` to `const cb = useCallback(() => callback(), deps);`.

As a side note, once either of the changes are made, it is recording 4 calls to the `jest.fn()` instead of 3 because it's called once with the initial prop and once for each rerender, so the test still fail.

**Comment by jackall3n** [comment]
Thanks for the in-depth description @mpeyper. I can see why it would work like that. I'll update the test accordingly.
