### ISSUE TITLE
Usage in close-to-real SSR environment?

### ISSUE THREAD

**Issue by xobotyi** [testing-library/react-hooks-testing-library#605]
Is there any way to test SSR functionality in environment close to real SSR?

I'm testing the hook that should fallback to noop during SSR, the hook declaration itself, as for now i'm checking SSR by testing `window` type: `typeof window !== 'undefined'`. Like this:
```ts
export const myAwesomeHook = typeof window === 'undefined' ? ()=>{} : ()=>{/*some real hook code*/}
```

When testing with jest in it's common env (jsdom) window object is obviously exists and there is no way to test that everything will be fine in SSR, since i gaij browser version of a hook.
If to switch environment to `node`, ssr tests failing with
```
    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: document is not defined

       7 |
    >  8 |     renderHook(() => myAwesomeHook());
         |     ^
       9 |

```

In this case renderHook improted from server: `import { renderHook } from '@testing-library/react-hooks/server';`

**Comment by mpeyper** [comment]
Hi @xobotyi, thanks for raising this issue.  I think it's being caused by this line:

https://github.com/testing-library/react-hooks-testing-library/blob/ef1d731c2a0d7d78e3b33b183d5b5dd927785aae/src/server/pure.ts#L16

We should move that into the `hydrate` function so we reference `document` when they want it to render for real.

Are you interested in submitting a PR for this @xobotyi?

**Comment by xobotyi** [comment]
@mpeyper i'm not really into SSR render flow, but if solution is only about that -i'll do.
