### ISSUE TITLE
Feature : test multiple hooks in same wrapper component and `mount` function

### ISSUE THREAD

**Issue by nivekithan** [testing-library/react-hooks-testing-library#615]
### Describe the feature you'd like:

As of now it is not possible to test multiple hooks in different `test components` but with same `wrapper component`. As of now we can  either test in different `wrapper component` or test in same `test components`. 

I like to have a feature that allows both these conditions. 

### Suggested implementation:

I looked into the code and this is what I came up with, tests are passing so it should be backwards compatible.

```ts

function createRenderHook<
  TProps,
  TResult,
  TRendererOptions extends object,
  TRenderer extends Renderer<TProps>
>(createRenderer: CreateRenderer<TProps, TResult, TRendererOptions, TRenderer>) {
  const renderHook = (
    callbacks: ((props: TProps) => TResult)[] | ((props: TProps) => TResult),
    options = {} as RenderHookOptions<TProps> & TRendererOptions
  ) => {
    const createResult = (callback: (props: TProps) => TResult) => {
      const { result, setValue, setError, addResolver } = resultContainer<TResult>()
      const renderProps = { callback, setValue, setError }
      let hookProps = options.initialProps

      const { render, rerender, unmount, act, ...renderUtils } = createRenderer(
        renderProps,
        options
      )

      render(hookProps)

      const rerenderHook = (newProps = hookProps) => {
        hookProps = newProps
        rerender(hookProps)
      }

      const unmountHook = () => {
        removeCleanup(unmountHook)
        unmount()
      }

      addCleanup(unmountHook)

      return {
        result,
        rerender: rerenderHook,
        unmount: unmountHook,
        ...asyncUtils(act, addResolver),
        ...renderUtils
      }
    }

    if (Array.isArray(callbacks)) {
      return callbacks.map((callback) => {
        return createResult(callback)
      })
    } else {
      return createResult(callbacks)
    }
  }

  return renderHook
}
```

### Teachability, Documentation, Adoption, Migration Strategy:

The above code should allow the users to use this code in this manner 

```ts

const result  = renderHook(() => useState(1)) // Only one test component

const [result1, result2] = renderHook([() => useState(1), () => useState(2)]) // Multiple test components

```

### Another Feature

There is also another feature I would  love to have. That is `mount` function similar to  `rerender` only difference is that it will only mount the component for the first time after invoking this function.

For backwards compatible, we could add another field in `option` something like this

```ts
const [result1, result2] = renderHook( [ () => useState(1), () => useState(2) ],  { dontMount : true}) 
````
But i do think this feature will be only useful in testing multiple hooks

### Note

I didnt really spend lot of time familiarizing with the lib, so solution I specified could be wrong. 

If I were to get some help,  I will have no problem in implementing all it by myself.

**Comment by nivekithan** [comment]
Regarding the mount function.

```ts
 const renderHook = (
    callbacks: ((props: TProps) => TResult)[] | ((props: TProps) => TResult),
    options = {} as RenderHookOptions<TProps> & TRendererOptions
  ) => {
    const createResult = (callback: (props: TProps) => TResult) => {
      const { result, setValue, setError, addResolver } = resultContainer<TResult>()
      const renderProps = { callback, setValue, setError }
      let hookProps = options.initialProps

      const { render, rerender, unmount, act, ...renderUtils } = createRenderer(
        renderProps,
        options
      )
    // change
     if (!options.dontMount) {
        render(hookProps)
      }
    
      const mount = () => { 
        render(hookProps)   
      }

      const rerenderHook = (newProps = hookProps) => {
        hookProps = newProps
        rerender(hookProps)
      }

      const unmountHook = () => {
        removeCleanup(unmountHook)
        unmount()
      }

      addCleanup(unmountHook)

      return {
        result,
        mount, // Change
        rerender: rerenderHook,
        unmount: unmountHook,
        ...asyncUtils(act, addResolver),
        ...renderUtils
      }
    }
   ```

 ```ts

export type RenderHookOptions<TProps> = {
  initialProps?: TProps,
  dontMount ?: boolean
}
 ```

The tests also passing but I am not sure weather it is the best way to implement  this or not?

**Comment by joshuaellis** [comment]
It'd be good to understand why this is needed? To me, it brings a bit of unnecessary overhead and if i'm unit testing something, surely I want it to be in isolation? Otherwise I might consider composing the component and using `testing-library-react` to render this?

**Comment by nivekithan** [comment]
@joshuaellis  I am actually creating  my own version of client library for [supabase](https://github.com/supabase/supabase). Which can handle caching of requests and some other features. 

I expose those features using custom hooks ( a lot similar to `react-query` ).  Each hook gets access to the cache object through the `context`. If the context is different then the cache will be also different.


Now lets say if I were to test the cache feature. As of now only way for me to do that will be something like this

```tsx
const  {result} = renderHook( () => {
 return {
   first : useCustomHook(),
   second : useCustomHook()
}
}, { wrapper : <Wrapper /> })
```

This approach has some problems like 

1. It does not resemble the way most likely the hooks will be used, users most likely will using the hooks in different components not in same component.

2. `unmount` will unmount the whole component. For example assume that I want to test the cache will persist even  when the  `first : useCustomHook()` gets unmounted.  I cant really check that since unmounting `first : useCustomHook()` will also unmount the `second : useCustomHook()`

These are just a subset of problems I am facing. 

Since I only care about the results of  my `useCustomHook` I dont really see need to use `react-testing-libary` and then composes the components just to check the results of `hooks`( I am not really sure weather it is even possible to do that).

I can understand my use case is not common but I am hoping this feature will be implementated

**Comment by mpeyper** [comment]
I'm not sure your suggested implementation is going to work as you intend:

```ts
      const { render, rerender, unmount, act, ...renderUtils } = createRenderer(
        renderProps,
        options
      )

      render(hookProps)
```

This snippet is going to create a new react root to render each callback in, so they won't be sharing the same instance of the `wrapper` component.  You'll end up with one render of

```tsx
<ErrorBoundary>
  <Suspense>
    <Wrapper>
      <TestComponent>
        {callback[0]()}
      </TestComponent>
    </Wrapper>
  </Suspense>
</ErrorBoundary>
```

and another of

```tsx
<ErrorBoundary>
  <Suspense>
    <Wrapper>
      <TestComponent>
        {callback[1]()}
      </TestComponent>
    </Wrapper>
  </Suspense>
</ErrorBoundary>
```

whereas I assume you actually want

```tsx
<ErrorBoundary>
  <Suspense>
    <Wrapper>
      <TestComponent>
        {callback[0]()}
      </TestComponent>
      <TestComponent>
        {callback[1]()}
      </TestComponent>
    </Wrapper>
  </Suspense>
</ErrorBoundary>
```

_(Note: these are representative structures, not actually how it works)._

From here on, I'll assume we could figure out how to run them all in the same react root and address the intent of the proposal.

I think this change has the potential to be a bit of a slippery slope for us.  While I sympathise with your use case, especially about around `unmount` being all or nothing with the currently available approaches, this proposal lands in an awkward spot of adding complexity to the API while not being flexible enough to support other similar use cases.

For instance, what about:
* multiple hooks with different `initialProps`
* nested components instead of siblings
* rerendering/unmounting a subset of the hooks together
* using the result of one hook as an input for another
* wait for the next render of a specific hook

Your proposal seems relatively simple on the surface, but it opens the door to more complex and difficult to implement use cases which I'm not sure we really want to take on.

I tend to agree with @joshuaellis that if you actually care about the structure composition of the underlying components and want to the control of when the mount/unmount, perhaps you are better off actually rendering components with `@testing-library/react`:

```ts
const results = {};
function TestComponent({ id, hook }) {
  results[id] = hook();
  return null;
}

render(
  <Wrapper>
    <TestComponent id="first" hook={() => useState(1)} />
    <TestComponent id="second" hook={() => useState(2)} />
  </Wrapper>
);

expect(results.first[0]).toBe(1)
expect(results.second[0]).toBe(2)
```

As for the `mount`/`dontMount` feature, I'm not sure when you would want to delay the mounting of the component (and consequently the execution of the hook) and what advantage that gives you.  Could you describe a use case where this would be useful?

Assuming there is a need for such a feature, generally I prefer the option to be written in the positive (i.e. `mount: false` or over `dontMount: true`).  I'd also only return `mount` from `renderHook` if the initial mount didn't occur to prevent them from calling it by mistake.  That might take some messing around with function overloads or conditional types to get TS to play nicely with it though.

**Comment by nivekithan** [comment]
It seems that rendering `react components` using `@testing-libary/react` is only going to will suit my use case. I will be using that itself

When I changed the code like above. I expected the resultant structure to look something like this

```jsx

<Wrapper>
 <ErrorBoundary>
   <Suspense>
       <TestComponent>
         {callback[0]()}
       </TestComponent>
   </Suspense>
 </ErrorBoundary>


 <ErrorBoundary>
   <Suspense>
      <TestComponent>
         {callback[0]()}
       </TestComponent>
   </Suspense>
 </ErrorBoundary>
</Wrapper>
```

So that `unmount` and `rerender` will only affect the testcomponent specific to that callback, not the whole tree.

In this way it can support `rerendering/unmount` of only subset of hooks, using result one hook of as a props to another ( using `mount/dontMount` option), wait for rerender of specific hook .

I didnt expect the structure will look this

```
<ErrorBoundary>
  <Suspense>
    <Wrapper>
      <TestComponent>
        {callback[0]()}
      </TestComponent>
      <TestComponent>
        {callback[1]()}
      </TestComponent>
    </Wrapper>
  </Suspense>
</ErrorBoundary>

```

I wanted `dontMount` option  so that I can control which components gets rendered at what time. Since I am making `custom hooks` which makes `api` calls, having that option allows me to test different conditions that might rise.

If rerendering multiple hooks is not going to be supported then I dont think this option could be useful in any cases.

**Comment by mpeyper** [comment]
Currently, the `Wrapper` inside the the Suspense and Error boundaries so that it can also utilise those features if required, although I think in practise few wrappers would.  You can see the order [here](https://github.com/testing-library/react-hooks-testing-library/blob/main/src/helpers/createTestHarness.tsx#L30-L37). The other issue is that the `createRenderer` call creates the whole tree and a new render root for them so work would need to be done to prevent that from occurring, although we would still want a new root for seperate calls to `renderHook`.

> I wanted `dontMount` option so that I can control which components gets rendered at what time. Since I am making `custom hooks` which makes `api` calls, having that option allows me to test different conditions that might rise.
> 
> If rerendering multiple hooks is not going to be supported then I dont think this option could be useful in any cases.

That makes sense.  Thanks for explaining further.

How do you feel about this feature now, given the extra context?  I'm happy to continue discussing and refining the idea if you want to, but I do think there is a long way to go before it is viable as something we would want to implement.

**Comment by nivekithan** [comment]
Well at first I thought it will be simple feature to implement, I never expected it to be this complex, so now I dont think I have enough knowledge about the repo to discuss it further. 

So you can close the issue if you want.

**Comment by mpeyper** [comment]
Thanks for your time and effort. Happy to reopen if anyone want to discuss further.

**Comment by peterkhayes** [comment]
I encountered similar problems as @nivekithan when testing a hooks-based caching system. For now I'm using the semi-workaround in https://github.com/testing-library/react-hooks-testing-library/issues/615#issuecomment-835814029, but if sharing one wrapper between multiple `renderHook` calls ever becomes possible, I'd love to know!
