### ISSUE TITLE
hooks not render in wrapper navigation react native 

### ISSUE THREAD

**Issue by YOEL311** [testing-library/react-hooks-testing-library#691]
- `react-hooks-testing-library` version:
- `react` version:     "react": "17.0.1",
- `node` version: 14.17.1
- `npm` (or `yarn`) version: yarn 1.22.10

 react-native project

### Relevant code or config:

```js
this is my wrapper 

const wrapper = ({ route }) => (
  <ReactQueryCacheProvider queryCache={queryCache}>
    <Provider store={store}>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen
            initialParams={{ name: route }}
            component={FilterScreen}
            name={'R'}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </Provider>
  </ReactQueryCacheProvider>
);

this my test 
 const { result, rerender } = renderHook(() => useFilterKey(), {
      wrapper,
      initialProps: {
        route: FEED_ROUTES.CHECKS,
      },
    });


```
Stack.Screen doesn't get children
which way can I render my hooks test this scenario in my navigation wrapper?

thanks

**Comment by mpeyper** [comment]
Hi @YOEL311,

Please review the [docs](https://react-hooks-testing-library.com/usage/advanced-hooks#context) on hooks requiring context.  The wrapper is provided the `TestComponent` as `children`, but it must render it somewhere for the hook to be called:

```ts
const wrapper = ({ route, children }) => (
  <ReactQueryCacheProvider queryCache={queryCache}>
    <Provider store={store}>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen
            initialParams={{ name: route }}
            component={children} // maybe here instead of the component?
            name={'R'}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </Provider>
  </ReactQueryCacheProvider>
);

 const { result, rerender } = renderHook(() => useFilterKey(), {
      wrapper,
      initialProps: {
        route: FEED_ROUTES.CHECKS,
      },
    });
```

Note that this library is for testing a hook _without_ a component (which is why I replaced `FilterScreen` in the wrapper with our `TestComponent` in `children`), not for testing components that use hooks.  If that's what you want then you should instead be using `@testing-library/react` and just rendering the component.

**Comment by YOEL311** [comment]
Your response makes sense
Thank you!
