### ISSUE TITLE
How to test a custom hook that uses a reducer via useContext

### ISSUE THREAD

**Issue by WillyRamirez** [testing-library/react-hooks-testing-library#703]
Thank you for creating/maintaining this awesome lib. Please note this is not a bug report, but as suggested by @mpeyper in #124 I created a new issue anyway.

- `react-hooks-testing-library` version: 7.0.2
- `react` version: 16.13.1
- `react-native`: 0.63.3
- `react-test-renderer` version (if applicable): 16.13.1
- `node` version: 15.8
- `npm` (or `yarn`) version: yarn 1.22.10

### Relevant code or config:

**custom hook (UseMeasurements.ts)**
```js


export const useMeasurements = () => {
  const { state, dispatch } = useContext(MeasurementContext);

  const getMeasurement = async (measurementId: number) => {
    console.log('I AM HERE: ', dispatch);
    dispatch({ type: types.GET_MEASUREMENT });
    const response = await api.getMeasurement(measurementId);

    if (response.ok) {
      dispatch({
        type: types.GET_MEASUREMENT_SUCCESS,
        payload: { measurement: response.data },
      });
    } else {
      // todo: error handling
    }
  };

  return {
    getMeasurement,
  };
}
```

**Test file (UseMeasurementsTests.tsx)**
```js

it('allows to getMeasurement', () => {
  const wrapper = ({ children }) => <MeasurementContextProvider>{children}</MeasurementContextProvider>
  const { result, waitForNextUpdate } = renderHook(() => useMeasurements(), { wrapper });

  act(async () => {
    await result.current.getMeasurement(1)
  })

  expect(dispatch).toHaveBeenCalled();
})
```

**Context (MeasurementContext.tsx)**
```js
export const MeasurementContext = React.createContext<{
  state: State;
  dispatch: (action: Action) => void;
}>({
  state: initialState,
  dispatch: () => {},
});

const measurementReducer = (state: State, action: Action) => {
  // irrelevant 
};

export const MeasurementContextProvider: React.FC = ({ children }) => {
  const [state, dispatch] = useReducer(measurementReducer, initialState);

  return (
    <Measurement.Provider value={{ state, dispatch }}>
      {children}
    </Measurement.Provider>
  );
};
```

### What you did:

I have a custom hook that uses a reducer via a useContext hook. I want to test and see if the dispatch method has been called.

### What happened:

It says the dispatch method has not been called, but the console.log line right before it logs a line in the console. Which is expected in the example above which I simplified for the sake of this issue. 
But I have tried mocking the entire MeasurementContext.tsx, and importing the dispatch mockFunction in the tests, but it still says:

```
   Expected number of calls: >= 1
    Received number of calls:    0
```
What would be the right approach?

(I can provide the mocks if necessary)

**Comment by skyboyer** [comment]
I don't see how this is a bug. You have set of options how to test your hook but I don't see easy way to access `dispatch()` internal variable which is part of the context.

## Approach 1. Mock context in your test

```
const mockDispatch = jest.fn(); // important to name it with "mock" as a prefix; https://jestjs.io/docs/es6-class-mocks#calling-jestmock-with-the-module-factory-parameter
jest.mock('path/MeasurementContext.js', () => {
  const mockedContext = new React.createContext();
  const mockedState = {};
  return {
    MeasurementContextProvider: ({ children }) => (
      <Measurement.Provider value={{ state: mockedState, dispatch: mockedDispatch }}>
        {children}
     </Measurement.Provider>
  );
 };
});
```

## Approach 2.  Check for api call instead.

I think you must already mock `api.*` to avoid real calls to server, right?
```
it('allows to getMeasurement', () => {
  const wrapper = ({ children }) => <MeasurementContextProvider>{children}</MeasurementContextProvider>
  const { result, waitForNextUpdate } = renderHook(() => useMeasurements(), { wrapper });

  act(async () => {
    await result.current.getMeasurement(1)
  })

  expect(api.getMeasurement).toHaveBeenCalledWith(1);
})
```

## Approach 3. Compose a component right in your test that would expose context's state and use @testing-library

Something like that(also to make this work `getMeasurement` must be wrapped into `useCallback` or it code will loop indefinitely)

```
function TestComponent(getMeasurementProps) {

  const { state } = useContext(MeasurementContext); 
  const { getMeasurement } = useMeasurements();

  useEffect(() => {
    getMeasurement(getMeasurementProps);
  }, [getMeasurementProps, getMeasurement]);

  return <textarea id="result">{JSON.stringify(state)}</textarea>
 
}
```

So instead of rendering hook directly, you will render that component, trigger custom hook to do something by changing props and check textarea's value to validate context data.

**Comment by joshuaellis** [comment]
To chime in here, it's a relatively straight forward hook in the sense it calls an API and updates the global state via Context. So adding to the above comment, I would probably mock the API call so you have complete control on what's being returned and can test if it's dispatching an error or success. But following from that, I would probably mock the context as `Approach 1` suggests. That way you can spy on the dispatch call.

In reality though, how is this hook going to be used? It might make more sense not to unit test the hook (since it's relatively straight forward) and rather test the component it lives in as a complete piece, this will give you confidence in how it reacts to the user's experience. Again, in this scenario, I would still be mocking the api. Probably with `mock-service-worker`.
