### ISSUE TITLE
Exceptions ignore on unmount

### ISSUE THREAD

**Issue by retyui** [testing-library/react-hooks-testing-library#718]
### To Reproduce

```bash
yarn create react-app my-app --template typescript
cd my-app/
yarn add --dev @testing-library/react-hooks react-test-renderer
# add tests (see below)
```

```tsx
// issue.test.ts
import {useEffect} from 'react';
import {renderHook} from '@testing-library/react-hooks'

const useMyHook = () => {
    useEffect(() => {
      return () => {
        throw new Error('Ops...') // ,<-- this error never catches by test
      }
    }, [])
  }

it('should fail on unmount', () => {
  expect(()=>{

    const {unmount, result} = renderHook(() => useMyHook())

    result.current

    unmount()
    
  }).toThrow()
})
```

**Comment by mpeyper** [comment]
I was going to leave a comment to check `result.error` instead of expecting it to throw directly in the test as I assumed this would be hitting the error boundary in the underlying test component we create, but I thought I'd check it before posting and strangely enough, it was being set either.

What's off is that the error boundary is not registering the error at all either, so I'm not sure if we have any ability at all to intercept this error at all.

I'm half wondering if react is not catching this on purpose in the "unmounting" case as the component is going away anyway, but perhaps if the effect cleanup was triggered by changing state it would perhaps end up in the error boundary?
