### ISSUE TITLE
Shallow check of custom hook declaration

### ISSUE THREAD

**Issue by anion155** [testing-library/react-hooks-testing-library#757]
### Describe the feature you'd like:

I think it would be useful to add ability to generate snapshot of all used hooks and it's parameters, to check custom hook for changes.

Something like this:
```
expect(renderHookSnapshot(() => useCustomHook())).toMatchSnapshot()
```

Maybe, it would be more useful as a separate package?

### Suggested implementation:

AST and check for all functions called with names started with 'use'?

### Describe alternatives you've considered:

For now, what I'm doing is mocking all used hooks, and manually check for call with specified params. But it does not provide ability to fail test if new hooks were added.

### Teachability, Documentation, Adoption, Migration Strategy:

There should be no changes to current implementation, so there is no migration strategy, at least none I see.

**Comment by mpeyper** [comment]
Hi @anion155, thanks for taking the time to put this issue together but unfortunately we won't be accepting a feature like this.

At `testing-library`, we value not testing implementation details (like which hook functions were specifically  called) but rather focus on testing things how the user would use them.  In our case, that means calling the hook function with some inputs and making assertions on the outputs.

Mocking should be used only in moderation to isolate side effects and/or reduce test complexity and in general we advise against snapshot testing and prefer explicit assertions of the values and behaviours you expect your users to see.

Let me put it this way, if you refactored your hook calls to be in a different order or combined a few into a custom hook or split a custom hook into multiple hooks, would you want your tests begin to fail and you must update your snapshots or rewrite your mocks, or would you rather have confidence the code still works as after the refactoring is complete because the tests still pass?  We value the latter.

I hope that makes some sense and gives you some insight into our values and the testing paradigms we promote here (we lean closer towards the integration end of the spectrum).  If you still feel strongly about this idea I encourage you to try it out in a seperate package and see how it goes.
