### ISSUE TITLE
Migration to react 18

### ISSUE THREAD

**Issue by modex98** [testing-library/react-hooks-testing-library#940]
when working with the library in a react 18 project i keep getting this warnings in the console 
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```
I just want to know if it (react 18) will be supported in the future in next versions

**Comment by victorheringer** [comment]
Looks like this lib [is been deprecated due to the merge with testing-library](https://github.com/testing-library/react-testing-library/pull/991), but there is a [PR](https://github.com/testing-library/react-hooks-testing-library/pull/927#pullrequestreview-1190819888) to make it compatible with react 18, but I guess the way is just migrate to react-testing-library `renderHook`, and this migration  guide may help https://github.com/testing-library/react-hooks-testing-library/blob/chore/migration-guide/MIGRATION_GUIDE.md

**Comment by MPSSreekar** [comment]
when working with the library in a React 18 project i keep getting these warnings in the console

What changes should be done to **render** is not working after upgrading to React 18.

return **render**(
        <Routes>
            <Route path="/:page/page/*" element={<Elements />} />
        </Routes>,
        { wrapper: WrapperWithRouter, ...options }
    );
    
    Do you know how I can change this?
    
    Your help is much appreciated 
    
    I appreciate any help you can provide.
